In [2]:
import torch
import numpy as np

### torch.tensor(factory) torch.Tensor(comstructor) torch.as_tensor(share memory)

In [3]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [4]:
o1 = torch.Tensor(data)
o2 = torch.tensor(data)
o3 = torch.as_tensor(data)#o3 o4与data使用同样的空间（地址） 若data改变则变
o4 = torch.from_numpy(data)#

In [5]:
print(o1)
print(o2)
print(o3)
print(o4)


tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3], dtype=torch.int32)


In [6]:
data[0] =111
print(o3)
print(o4)

tensor([111,   2,   3], dtype=torch.int32)
tensor([111,   2,   3], dtype=torch.int32)


### Reshape

In [7]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [9]:
print(t.size())
print(t.shape)

torch.Size([3, 4])
torch.Size([3, 4])


In [10]:
torch.tensor(t.shape).prod()
#元素数量与product of the shape's component 相同

tensor(12)

In [11]:
#直接方法获取 tensor内元素个数
t.numel()

12

### reshape a tensor in pytorch
元素个数相同

In [12]:
t.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [13]:
t.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [14]:
t.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

In [15]:
t.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

### squeezing 删除长度为1的维度或轴 and unsqueezing 增加一个长度为1的维度或轴

In [16]:
print(t.reshape([1,12]))
print(t.reshape([1,12]).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [17]:
print(t.reshape([1,12]).squeeze())
print(t.reshape([1,12]).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [18]:
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0))
print(t.reshape([1,12]).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


### flatten a tensor  去除所有除了1外的维度 (相当于压缩成1维的)

In [23]:
def flatten(t):
    t = t.reshape(1,-1)#-1 为自动计算
    t = t.squeeze()#去掉 为1的维度1
    return t

In [24]:
t = torch.ones(4,3)
t

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
flatten(t)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### concatenating cat

In [30]:
t1 = torch.tensor([
    [1,2],
    [3,4]
])
t1.shape

torch.Size([2, 2])

In [27]:
t2 = torch.tensor([
    [5,6],
    [7,8]
])

In [28]:
torch.cat((t1,t2),dim=0)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [29]:
torch.cat((t1,t2),dim=1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

## 展开

In [32]:
t1 = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [34]:
#stack 栈先进后出   heap 堆先进先出
t = torch.stack((t1,t2,t3))
print(t.shape)
t

torch.Size([3, 4, 4])


tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

### flatten

In [35]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [36]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [37]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [38]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### 不同维度的展开

In [42]:
print(t.shape)
print(t.flatten(start_dim=1).shape)
print(t.flatten(start_dim=1))

torch.Size([3, 4, 4])
torch.Size([3, 16])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])


### 展开一张RGB图片

In [51]:
r = torch.ones(1,2,2)
g = torch.ones(1,2,2) + 1
b = torch.ones(1,2,2) +2

img = torch.cat((r,g,b),dim=0)
print(img.shape)
print(img)


torch.Size([3, 2, 2])
tensor([[[1., 1.],
         [1., 1.]],

        [[2., 2.],
         [2., 2.]],

        [[3., 3.],
         [3., 3.]]])


In [52]:
print(img.flatten(start_dim=0).shape)
print(img.flatten(start_dim=0))

torch.Size([12])
tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])


In [54]:
print(img.flatten(start_dim=1).shape)
print(img.flatten(start_dim=1))

torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])


## 12 元素操作

In [55]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)

In [56]:
print(t1+2)

print(t1-2)

print(t1*2)

print(t1/2)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


In [57]:
print(t1.add(2))

print(t1.sub(2))

print(t1.mul(2))

print(t1.div(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])


### 广播机制 相当于会将a 补齐成 b 的形状

In [58]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

In [61]:
# t1+2 相当于
t1 + torch.tensor(np.broadcast_to(2,t1.shape),dtype = torch.float32)

tensor([[3., 4.],
        [5., 6.]])

In [62]:
t1 = torch.tensor([
    [1,1],
    [1,1]
], dtype=torch.float32)

t2 = torch.tensor([2,4], dtype=torch.float32)

print(t1.shape)
print(t2.shape)

torch.Size([2, 2])
torch.Size([2])


In [63]:
print(np.broadcast_to(t2.numpy(),t1.shape))

t1+t2

[[2. 4.]
 [2. 4.]]


tensor([[3., 5.],
        [3., 5.]])

### 比较

In [64]:
torch.tensor([1,2,3]) < torch.tensor([3,1,2])

tensor([ True, False, False])

In [66]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)
print(t.eq(0))
print(t.ge(0))#>=
print(t.gt(0))#>=
print(t.lt(0))#<=
print(t.le(7))#<=

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[False,  True, False],
        [ True, False,  True],
        [False,  True, False]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])
tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])


In [67]:
t.le(7)#相当于
t <= torch.tensor(
    np.broadcast_to(7,t.shape)
    ,dtype = torch.float32
)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [68]:
t.le(7)#相当于
t <= torch.tensor([
    [7,7,7],
    [7,7,7],
    [7,7,7]
], dtype=torch.float32)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

#### Element-Wise Operations Using Functions

In [69]:
print(t.abs())
print(t.sqrt())
print(t.neg())
print(t.neg().abs())


tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])
tensor([[0.0000, 2.2361, 0.0000],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])
tensor([[-0., -5., -0.],
        [-6., -0., -7.],
        [-0., -8., -0.]])
tensor([[0., 5., 0.],
        [6., 0., 7.],
        [0., 8., 0.]])


## 13Code For Deep Learning - ArgMax And Reduction Tensor Ops

In [70]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

#### reduction operation 相当于减少axes

In [71]:
print(t.sum(dim=0))
print(t[2].sum())


tensor([6., 6., 6., 6.])
tensor(12.)


In [72]:
t = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [73]:
print(t.max())
print(t.argmax())#没有指定axis的时候 返回的是 最大值的index 位置 （flatten 后的位置）
print(t.flatten())

tensor(5.)
tensor(11)
tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])


#### <font color='#8a00e6'>重点理解 </font>

In [74]:
print(t.max(dim=0))
print(t.argmax(dim=0))
print(t.max(dim=1))
print(t.argmax(dim=1))

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))
tensor([2, 1, 1, 2])
torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))
tensor([3, 1, 3])


In [76]:
t = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9]
], dtype=torch.float32)

In [78]:
print(t.mean())
print(t.mean().item())
print(t.mean(dim=0).tolist())
print(t.mean(dim=0).numpy())
print(t.mean(dim=1).tolist())
print(t.mean(dim=1).numpy())

tensor(5.)
5.0
[4.0, 5.0, 6.0]
[4. 5. 6.]
[2.0, 5.0, 8.0]
[2. 5. 8.]
