In [1]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

import torchvision 
import torchvision.transforms as transforms

torch.set_printoptions(linewidth=120)


In [2]:
train_set = torchvision.datasets.FashionMNIST(
    root = 'data/'
    ,train=True
    ,download=True
    ,transform = transforms.Compose([
        transforms.ToTensor()
    ])
)

In [3]:
class Nsetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels= 1,out_channels=6,kernel_size=5)
        self.conv2 = nn.Conv2d(in_channels= 6,out_channels=12,kernel_size=5)
        
        self.fc1=nn.Linear(in_features = 12*4*4, out_features = 12)
        self.fc2=nn.Linear(in_features = 12, out_features = 60)
        self.out=nn.Linear(in_features = 60, out_features = 10)
        
    def forward(self,t):
        t = F.relu(self.conv1(t))
        t = F.max_pool2d(t,kernel_size=2, stride = 2)
        
        t = F.relu(self.conv2(t))
        t = F.max_pool2d(t,kernel_size=2, stride = 2)
        
        t = F.relu(self.fc1(t.reshape(-1,12*4*4)))
        t = F.relu(self.fc2(t))
        t = self.out(t)
            
        
        return t
    

In [4]:
torch.set_grad_enabled(False)

In [5]:
network = Nsetwork()

In [6]:
sample = next(iter(train_set))

In [7]:
image,label = sample
image.shape

torch.Size([1, 28, 28])

In [8]:
image.unsqueeze(0).shape#this gives us a batch tish size1

torch.Size([1, 1, 28, 28])

In [9]:
pred = network(image.unsqueeze(0))

In [10]:
pred.shape

torch.Size([1, 10])

In [11]:
pred

tensor([[ 0.0762,  0.0581, -0.0430, -0.0218,  0.0099, -0.0099, -0.0914, -0.1973, -0.0021, -0.1038]])

In [15]:
label#这张图的实际类

9

In [16]:
pred.argmax(dim=1)

tensor([0])

In [17]:
F.softmax(pred,dim=1)

tensor([[0.1112, 0.1092, 0.0987, 0.1008, 0.1040, 0.1020, 0.0940, 0.0846, 0.1028, 0.0928]])

In [18]:
F.softmax(pred,dim=1).sum()

tensor(1.)

In [19]:
net1 = Nsetwork()

In [20]:
net1(image.unsqueeze(0))

tensor([[-0.1493, -0.0879, -0.1379, -0.0639,  0.0998,  0.0094,  0.1648,  0.0130,  0.1001,  0.0077]])

In [21]:
net2 = Nsetwork()

In [22]:
net2(image.unsqueeze(0))

tensor([[ 0.1220, -0.0894, -0.2222,  0.0363, -0.0939, -0.0816,  0.0079, -0.0089,  0.1153, -0.0074]])