In [1]:
import torch

In [20]:
t1 = torch.tensor([1,1,1])
print(t1)
t1.shape

tensor([1, 1, 1])


torch.Size([3])

In [3]:
t1.unsqueeze(dim=0)

tensor([[1, 1, 1]])

In [22]:
print(t1.unsqueeze(dim=1))
t1.unsqueeze(1).shape

tensor([[1],
        [1],
        [1]])


torch.Size([3, 1])

In [6]:
print(t1.shape)
print(t1.unsqueeze(dim=0).shape)
print(t1.unsqueeze(dim=1).shape)

torch.Size([3])
torch.Size([1, 3])
torch.Size([3, 1])


## PyTorch: Stack vs Cat

In [8]:
t1 = torch.tensor([1,1,1])
t2 = torch.tensor([2,2,2])
t3 = torch.tensor([3,3,3])

### Concatenating 连接 沿着一个现有的轴

In [9]:
torch.cat(
    (t1,t2,t3)
    ,dim =0
)

tensor([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [13]:
torch.cat(
    (
        t1.unsqueeze(0)
        ,t2.unsqueeze(0)
        ,t3.unsqueeze(0)
    )
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

### Stacking 连接 沿着一个新的轴

In [11]:
torch.stack(
    (t1,t2,t3)
    ,dim=0
)

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

In [14]:
torch.stack(
    (t1,t2,t3)
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [16]:
torch.cat(
    (
        t1.unsqueeze(1)
        ,t2.unsqueeze(1)
        ,t3.unsqueeze(1)
    )
    ,dim=1
)

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

## NumPy: Stack vs Concatenate

In [23]:
import numpy as np

In [24]:
t1 = np.array([1,1,1])
t2 = np.array([2,2,2])
t3 = np.array([3,3,3])

In [25]:
np.concatenate(
    (t1,t2,t3)
    ,axis = 0
)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [26]:
np.stack(
    (t1,t2,t3)
    ,axis = 0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [28]:
np.concatenate(
    (np.expand_dims(t1,0)
    ,np.expand_dims(t2,0)
    ,np.expand_dims(t3,0)
    )
    ,axis=0
)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [29]:
np.stack(
    (t1,t2,t3)
    ,axis=1
)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
??np.stack

Signature: np.stack(arrays, axis=0, out=None)
Source:   
@array_function_dispatch(_stack_dispatcher)
def stack(arrays, axis=0, out=None):
    """
    Join a sequence of arrays along a new axis.

    The ``axis`` parameter specifies the index of the new axis in the
    dimensions of the result. For example, if ``axis=0`` it will be the first
    dimension and if ``axis=-1`` it will be the last dimension.

    .. versionadded:: 1.10.0

    Parameters
    ----------
    arrays : sequence of array_like
        Each array must have the same shape.

    axis : int, optional
        The axis in the result array along which the input arrays are stacked.

    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what stack would have returned if no
        out argument were specified.

    Returns
    -------
    stacked : ndarray
        The stacked array has one more dimension than the input arrays.

    See Also


In [31]:
np.concatenate(
    (np.expand_dims(t1,1)
    ,np.expand_dims(t2,1)
    ,np.expand_dims(t3,1)
    )
    ,axis=1
)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])